apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pv-claim
  labels:
    tier: postgres
spec:
  storageClassName: rook-ceph-block
  resources:
    requests:
      storage: 5Gi
  accessModes:
    - ReadWriteOnce
