---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  name: simple-comment-section-registry
  namespace: flux-system
spec:
  image: yungen/simple-comment-section
  interval: 5m0s