---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: simple-comment-section-policy
spec:
  imageRepositoryRef:
    name: simple-comment-section-registry
  policy:
    semver:
      range: ">=1.0.0"
