apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: simple-comment-section-policy
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: simple-comment-section-registry
  policy:
    semver:
      range: >=1.0.0