apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pv-claim
  labels:
    tier: redis
spec:
  storageClassName: rook-ceph-block
  resources:
    requests:
      storage: 100Mi
  accessModes:
    - ReadWriteOnce
